### ISSUE TITLE
Class not found 'org/renpy/android/PythonActivity'

### ISSUE THREAD

**Issue by CikoXp** [kivy-garden/xcamera#15]
Builded my kivy apk with buildozer and installed on my Android 10 Pie (API 29), App crashes immediately after start and ADB Logcat give me this error.
After some days of research i founded the way to fix building the 1st apk only to populate the .buildozer folder and manually editing this file:

kivy_garden/xcamera/android_api.py

where at line 7 i changed:

AndroidPythonActivity = autoclass('org.renpy.android.PythonActivity')

with

AndroidPythonActivity = autoclass('org.kivy.android.PythonActivity').

This fix solves the error and Apk works as expected, but ther's a reason if github repo is not updated? Can someone consider to apply this update?
Or someone knows a way to set buildozer to auto edit this line before compile? Maybe a sort of patch?
Thanx for the help.

**Comment by AndreMiras** [comment]
Yes please make a pull request. The `renpy` was dropped some weeks ago and not all project made the transition it seems
